/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project1;
import java.sql.PreparedStatement;
import Project1.myconnection;
import javax.swing.JOptionPane;

/**
 *
 * @author jagadeeshwaranv
 */
public class Addemp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Addemp.class.getName());

    /**
     * Creates new form Addemp
     */
    public Addemp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Id = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        Number = new javax.swing.JTextField();
        Aadhar = new javax.swing.JTextField();
        Dob = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Academy Engraved LET", 0, 36)); // NOI18N
        jLabel1.setText("ADD NEW EMPLOYEE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(217, 44, 404, 43);

        jLabel2.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(218, 169, 78, 29);

        jLabel4.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel4.setText("ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(218, 266, 27, 29);

        jLabel5.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel5.setText("AGE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(218, 328, 53, 29);

        jLabel6.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel6.setText("GENDER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(218, 386, 108, 29);

        jLabel7.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel7.setText("NUMBER");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(214, 441, 112, 29);

        jLabel8.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel8.setText("DOB");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(218, 497, 51, 29);

        jLabel9.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel9.setText("AADHAR ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(212, 578, 146, 29);

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(420, 170, 250, 23);

        jLabel10.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel10.setText("PASSWORD");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(218, 219, 140, 29);

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(420, 220, 250, 23);
        getContentPane().add(Id);
        Id.setBounds(420, 267, 250, 23);

        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        getContentPane().add(Age);
        Age.setBounds(420, 329, 250, 23);
        getContentPane().add(Gender);
        Gender.setBounds(420, 387, 250, 23);

        Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberActionPerformed(evt);
            }
        });
        getContentPane().add(Number);
        Number.setBounds(420, 442, 250, 23);
        getContentPane().add(Aadhar);
        Aadhar.setBounds(420, 579, 250, 23);

        Dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DobActionPerformed(evt);
            }
        });
        getContentPane().add(Dob);
        Dob.setBounds(420, 498, 250, 23);

        Add.setText("add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(410, 670, 72, 23);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 670, 90, 23);

        jPanel1.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/jagadeeshwaranv/Desktop/task1/foodemploye.jpeg")); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(-180, -20, 610, 530);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(890, 150, 430, 490);

        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/jagadeeshwaranv/Desktop/task1/wooden-planks-with-blurred-resta.jpeg")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, -20, 1720, 940);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/jagadeeshwaranv/Desktop/task1/foodemploye.jpeg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(920, 30, 590, 670);

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/jagadeeshwaranv/Desktop/task1/foodemploye.jpeg")); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(800, 120, 720, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberActionPerformed

    private void DobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DobActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
         String n= Name.getText();
        System.out.println(n);
       String p = new String(Password.getPassword());
        System.out.println(p);
               String i = Id.getText();
               System.out.println(i);
               String a=Age.getText();
               System.out.println(a);
               String g=Gender.getText();
               System.out.println(g);
               String nm=Number.getText();
               System.out.println(n);
               String d=Dob.getText();
               System.out.println(nm);
               String ad=Aadhar.getText();
               
         PreparedStatement ps;
        String query = "insert into employe(Name,Password,Id ,Age,Gender,Number,Dob,Aadharid )values(?,?,?,?,?,?,?,?)";
        try 
        {
            ps=myconnection.getConnection().prepareStatement(query);
            ps.setString(1,n);
              ps.setString(2,p);
               ps.setString(3,i);
                ps.setString(4,a);
                ps.setString(5, g);
                                ps.setString(6, nm);
                                                ps.setString(7, d);
                                                                ps.setString(8, ad);
                if(ps.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null, "add details completed");
                }
            
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Employe e =new Employe();
       e.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Addemp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Aadhar;
    private javax.swing.JButton Add;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Dob;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Number;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
