/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project1;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Project1.myconnection;
import javax.swing.JOptionPane;


/**
 *
 * @author jagadeeshwaranv
 */
public class Deleteemp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Deleteemp.class.getName());

    /**
     * Creates new form Deleteemp
     */
    public Deleteemp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Number = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Aadhar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Dob = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(Gender);
        Gender.setBounds(329, 428, 268, 23);

        jLabel5.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel5.setText("AGE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(127, 369, 53, 29);

        jLabel6.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel6.setText("GENDER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(127, 427, 108, 29);

        Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberActionPerformed(evt);
            }
        });
        getContentPane().add(Number);
        Number.setBounds(329, 483, 268, 23);

        jLabel7.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel7.setText("NUMBER");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(123, 482, 112, 29);
        getContentPane().add(Aadhar);
        Aadhar.setBounds(329, 620, 268, 23);

        jLabel8.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel8.setText("DOB");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(127, 538, 51, 29);

        Dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DobActionPerformed(evt);
            }
        });
        getContentPane().add(Dob);
        Dob.setBounds(329, 539, 268, 23);

        jLabel9.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel9.setText("AADHAR ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(121, 619, 146, 29);

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(329, 211, 268, 23);

        jLabel10.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel10.setText("PASSWORD");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(127, 260, 140, 29);

        jLabel1.setFont(new java.awt.Font("Academy Engraved LET", 0, 36)); // NOI18N
        jLabel1.setText("DELETE EMPLOYEE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(178, 14, 364, 43);

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(329, 261, 268, 23);

        jLabel2.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(127, 210, 78, 29);
        getContentPane().add(Id);
        Id.setBounds(329, 308, 268, 23);

        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        getContentPane().add(Age);
        Age.setBounds(329, 370, 268, 23);

        jLabel4.setFont(new java.awt.Font("Academy Engraved LET", 0, 24)); // NOI18N
        jLabel4.setText("ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(127, 307, 27, 29);

        jLabel3.setText("EMP ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(242, 94, 43, 17);
        getContentPane().add(ID);
        ID.setBounds(367, 94, 107, 23);

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(283, 147, 72, 23);

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(213, 667, 72, 23);

        jButton3.setText("REMOVE EMPLOYE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(344, 667, 148, 23);

        jPanel1.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/jagadeeshwaranv/Desktop/task1/foodemploye.jpeg")); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(-290, -30, 680, 510);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(790, 200, 390, 440);

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/jagadeeshwaranv/Desktop/task1/wooden-planks-with-blurred-resta.jpeg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1730, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberActionPerformed

    private void DobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DobActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s = ID.getText();
        System.out.println(s);
        PreparedStatement ps;
        ResultSet rs;
        try {
            String query="select *from employe where Id =?";
            ps=Project1.myconnection.getConnection().prepareStatement(query);
            ps.setString(1, s);
            rs = ps.executeQuery();
            if(rs.next()){
                Name.setText(rs.getString("Name"));
                Password.setText(rs.getString("Password"));
                Id.setText(rs.getString("Id"));
                Age.setText(rs.getString("Age"));
               Gender.setText(rs.getString("Gender"));
                Number.setText(rs.getString("Number"));
                Dob.setText(rs.getString("Dob"));
                  Aadhar.setText(rs.getString("Aadharid"));
               
               
            }
            else{
                JOptionPane.showMessageDialog(null, "Mobile number is invalid");
            }
        
         }
        catch (Exception ex){
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String s=ID.getText();
        int a= JOptionPane.showConfirmDialog(null, "do you want to delete..?","select",JOptionPane.YES_NO_CANCEL_OPTION);
        PreparedStatement ps;
        if(a==0){
            String query = "delete from employe where Id=?";
            try {
                ps=myconnection.getConnection().prepareStatement(query);
                ps.setString(1, s);
                if(ps.executeUpdate()>0){
                    JOptionPane.showMessageDialog(null, "successfully deleted");
                }
                else{
                    JOptionPane.showMessageDialog(null, "details not deleted");
                }
            }
            catch (Exception e){
                System.out.println(e);
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       Employe e= new Employe();
       e.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Deleteemp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Aadhar;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Dob;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Number;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
