/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Project1;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Project1.myconnection;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jagadeeshwaranv
 */
public class Order extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Order.class.getName());

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Price = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(Price);
        Price.setBounds(335, 451, 64, 23);

        jLabel1.setFont(new java.awt.Font("Academy Engraved LET", 0, 36)); // NOI18N
        jLabel1.setText("ADD ORDER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 70, 228, 43);

        jLabel2.setText("FOOD NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(187, 252, 76, 17);

        jLabel3.setText("FOOD ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(187, 318, 52, 17);

        jLabel4.setText("QUANTITY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(187, 388, 61, 17);

        jLabel5.setText("PRICE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(187, 454, 37, 17);
        getContentPane().add(Name);
        Name.setBounds(335, 249, 64, 23);
        getContentPane().add(Id);
        Id.setBounds(335, 315, 64, 23);
        getContentPane().add(Quantity);
        Quantity.setBounds(335, 385, 64, 23);

        jLabel6.setText("FOOD ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(232, 131, 52, 17);

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID);
        ID.setBounds(310, 130, 64, 23);

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(252, 181, 72, 23);

        Add.setText("ADD ORDER");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(210, 580, 105, 23);

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(80, 580, 72, 23);

        jButton2.setText("SHOW ORDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 580, 118, 23);

        jButton3.setText("BILL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(570, 580, 72, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/jagadeeshwaranv/Desktop/task1/login.jpeg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-30, 0, 1500, 980);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s = ID.getText();
        System.out.println(s);
        PreparedStatement ps;
        ResultSet rs;
        try {
            String query="select *from food where Code=? or Name=?";
            ps=Project1.myconnection.getConnection().prepareStatement(query);
            ps.setString(1, s);
            ps.setString(2, s);
            rs = ps.executeQuery();
            if(rs.next()){

                Name.setText(rs.getString("Name"));
                Id.setText(rs.getString("Code"));
                Quantity.setText(rs.getString("Quantity"));
                Price.setText(rs.getString("Price"));

            }
            else{
                JOptionPane.showMessageDialog(null, "Id  is invalid");
            }
        }
        catch (Exception ex){
            System.out.println(ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
                 String n = Name.getText();
               System.out.println(n);
               String c=Id.getText();
               System.out.println(c);
               String q=Quantity.getText();
               System.out.println(q);
               String p=Price.getText();
               System.out.println(p);
                              
         PreparedStatement ps;
        String query = "insert into Addorder (Name,Code,Quantity,Price )values(?,?,?,?)";
        try 
        {
            ps=myconnection.getConnection().prepareStatement(query);
            ps.setString(1,n);
              ps.setString(2,c);
               ps.setString(3,q);
                ps.setString(4,p);
                                if(ps.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null, "add details completed");
                }
            
        }
        catch(Exception ex){
            System.out.println(ex);
        }

    }//GEN-LAST:event_AddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        loginpage f=new loginpage();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Addorder f=new Addorder();
        f.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Bill f=new Bill();
        f.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Order().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
